### ISSUE TITLE
Concerns about curve flattening concept

### ISSUE THREAD

**Issue by sergiev** [open-data-science/ultimate_posts#9]
Hi, thanks for the post! Hope you're OK.

There is the [source](https://medium.com/@joschabach/flattening-the-curve-is-a-deadly-delusion-eea324fe9727) (also [russian translation](https://localcrew.ru/coronacurve)) claiming that the concept of _curve flattening_ is unrealistic due to low capacity of healthcare system even in the most optimistic scenarios. Please, check it: maybe it's worth noting in the post. 

Thank you.

**Comment by Hiyorimi** [comment]
Feel free to submit a Pull Request :)
